name: Check changed GPML files

on:
  push:
    branches:
      - master
      
  pull_request:
    branches:    
      - master

jobs:
  get_changed_files:
    runs-on: ubuntu-latest
    name: Get changed GPML files
    steps:
      - uses: actions/checkout@v3
      - id: foo
        uses:  AkMo3/WikiPathway-composite-actions/changed-files@v1 
      - run: echo random-number ${{ steps.foo.outputs.changed_gpml_file_name }}
        shell: bash
 
